# Generated by Django 4.0.5 on 2022-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='홍길동', max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, default=25, max_length=3, null=True)),
                ('school', models.CharField(blank=True, default='CAU', max_length=30, null=True)),
                ('major', models.CharField(blank=True, default='CSE', max_length=50, null=True)),
                ('pup_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
