# Generated by Django 4.0.5 on 2022-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='Hello world!', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='view_auth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
